### ISSUE TITLE
Helmet Mounting Suggestions?

### ISSUE THREAD

**Issue by DanielArnett** [platypii/BASElineFlightComputer#5]
@platypii Do you have any suggestions for mounting the XGPS160 to the helmet? I have a Flysight mount already attached, but I don't mind removing it.

**Comment by platypii** [comment]
I have a mount that I'm hoping to start selling soon. Shoot me an email admin@baseline.ws if you want one before the store is up.
![mount1sm](https://user-images.githubusercontent.com/1766297/52095800-4925df00-2579-11e9-919b-5170be3703d1.jpg)
